# -*- coding: utf-8 -*-
"""4. Analysis of the Data -TGVD Team Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tP_0DLhEbT7D-2hTA9mP2upKi6JBd0ti

# **4 Analysis of the data**

On top of the selected dataset, you must develop different analytics. In this section, the usage
of the Dataframe API is mandatory. In addition to the materials at ALUD, you could need to
check the following links:

● Spark SQL, DataFrames and Datasets Guide:
https://spark.apache.org/docs/latest/sql-programming-guide.html

● Spark SQL API Reference:
https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/index.html
Spark SQL API includes a wide set of functions that could be useful to achieve your goals at this
section. It would be nice if you take a look before starting coding anything:

● Functions:
https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/functions.html
All the analytics must be launched in the computation cluster you have deployed in section 3.

The source code implementing the analytics could be in a single or multiple *.py files. The
results must be saved in HDFS. Later, you must use the proper tool (Colab, JupyterLab,
Zeppelin…) to present the results.

If you select a dataset from sources like Kaggle, you must avoid implementing any analytics
already done by the community

## Dataset Loading - In pure Python
"""

import pandas as pd

dataset_path = "fatal-police-shootings-data.csv"

dataset = pd.read_csv(dataset_path)

dataset.head(5)

dataset["manner_of_death"].unique()

"""## Spark Initialization"""

def save_to_hdfs(df, path, format="parquet", mode="overwrite"):
    writer = df.write.format(format).mode(mode)
    if format == "csv":
        writer = writer.option("header", "true")
    writer.save(path)



# !pip install pyspark findspark

import findspark
findspark.init()

import pyspark
from pyspark.sql import SparkSession
spark = SparkSession.builder.appName("TGVD Project").getOrCreate()

dataset = spark.read.csv(dataset_path, header=True, inferSchema=True)

dataset.printSchema()

"""Ya tenemos el dataset importado en spark aquí"""

dataset.show(5, truncate=False)

"""## 4.1 Analytical questions

1. Does the presence of a body camera have an impact on the likelihood of a fatal shooting?
"""

from pyspark.sql.functions import round, sum as _sum
from pyspark.sql.functions import col

# Group by body_camera and count
body_camera_impact = dataset.groupBy("body_camera").count()

# Get total count for normalization
total = dataset.count()

# Add percentage column
body_camera_impact_with_percent = body_camera_impact.withColumn(
    "percentage", round((col("count") / total) * 100, 2)
)

# Show the results
body_camera_impact_with_percent.show()

"""This result indicates that in 11.22% of fatal cases, the officers were wearing body cameras while in 88.78% of cases they were not wearing any. However, this does not mean that body cameras reduce fatal shootings. The dataset does not contain information about non-fatal shootings, so we cannot calculate if there is a significant difference. Let's try to collect some more insights of the use of body cameras.


"""

from pyspark.sql.functions import collect_set, size

# Aggregate weapon types per body_camera status
weapon_sets = dataset.groupBy("body_camera").agg(
    collect_set("armed").alias("weapons_used")
)

# Count number of unique weapon types
weapon_variety = weapon_sets.withColumn(
    "weapon_variety", size("weapons_used")
).select("body_camera", "weapon_variety")

# Show result
weapon_variety.show()

save_to_hdfs(body_camera_impact_with_percent, "/user/analysis/body_camera_impact")
save_to_hdfs(weapon_variety, "/user/analysis/weapon_variety_by_body_camera")

"""These results could indicate that encounters without body cameras tend to involve a broader and more unpredictable range of weapons. While this does not imply that the use of body cameras reduces the severity of the incidents, it could promote a change in the behavior of either officers or civilians when they know they're being recorded.


2. Are certain cities or states overrepresented?
"""

from pyspark.sql.functions import desc

# Count number of incidents per state
state_counts = dataset.groupBy("state").count().orderBy(desc("count"))
state_counts.show(10, truncate=False)

# Count number of incidents per city
city_counts = dataset.groupBy("city").count().orderBy(desc("count"))
city_counts.show(10, truncate=False)

"""It appears that certain states have more incidents, but without the population size it's not definitive overrepresentation—just higher counts. We will calculate the number of fatal shootings by the population of each state in 2020."""

from pyspark.sql.functions import col, round, year

# Create population DataFrame
population_data = [
    ("AL", 5033094), ("AK", 733017), ("AZ", 7187135), ("AR", 3014546), ("CA", 39521958),
    ("CO", 5787129), ("CT", 3579918), ("DE", 991928), ("DC", 670917), ("FL", 21592035),
    ("GA", 10732888), ("HI", 1451252), ("ID", 1849415), ("IL", 12799088), ("IN", 6790497),
    ("IA", 3191141), ("KS", 2938172), ("KY", 4508318), ("LA", 4652301), ("ME", 1364571),
    ("MD", 6177935), ("MA", 6994598), ("MI", 10072703), ("MN", 5710735), ("MS", 2958536),
    ("MO", 6154744), ("MT", 1087230), ("NE", 1963387), ("NV", 3116967), ("NH", 1378756),
    ("NJ", 9272794), ("NM", 2118606), ("NY", 20105171), ("NC", 10449652), ("ND", 779563),
    ("OH", 11798905), ("OK", 3965415), ("OR", 4243779), ("PA", 12996143), ("RI", 1096530),
    ("SC", 5132249), ("SD", 887948), ("TN", 6927904), ("TX", 29239570), ("UT", 3284077),
    ("VT", 642977), ("VA", 8637615), ("WA", 7727209), ("WV", 1791646), ("WI", 5897375), ("WY", 577681)
]

columns = ["state", "population_2020"]
population_df = spark.createDataFrame(population_data, columns)

# Filter dataset for 2020 incidents only
dataset_2020 = dataset.filter(year("date") == 2020)

# Count incidents by state for 2020 only
state_counts_2020 = dataset_2020.groupBy("state").count()

# Join with population data and compute per-capita rate
joined_df_2020 = state_counts_2020.join(population_df, on="state")
result_df = joined_df_2020.withColumn(
    "incidents_per_100k", round((col("count") / col("population_2020")) * 100000, 2)
).orderBy(desc("incidents_per_100k"))


# Show top 10 overrepresented states
result_df.show(10, truncate=False)

save_to_hdfs(state_counts, "/user/analysis/state_counts_total")
save_to_hdfs(city_counts, "/user/analysis/city_counts_total")
save_to_hdfs(result_df, "/user/analysis/incidents_per_capita_2020")

"""After calculating the number of incidents per capita, some smaller states appear overrepresented in fatal police shootings. Alaska, for example, had the highest rate at 0.82 incidents per 100,000 people, despite having a low number of total incidents. Other less-populated states like Nevada and Montana also ranked high per capita.

3. Do fatal shootings involving mental health crises differ by region or race?
"""

# Filter dataset for incidents with mental health crisis
mental_health_crisis_df = dataset.filter(dataset.signs_of_mental_illness == 'true')

# Group by state
mental_health_by_state = mental_health_crisis_df.groupBy("state").count().orderBy("count", ascending=False)
mental_health_by_state.show(truncate=False)

# Group by race
mental_health_by_race = mental_health_crisis_df.groupBy("race").count().orderBy("count", ascending=False)
mental_health_by_race.show(truncate=False)

"""We can see that California has the highest number of incidents involving mental health (174), followed by Florida (93) and Texas (88), which is consistent with their large populations.
Racially, White individuals (W) are the most represented group in these incidents (692 cases), followed by Black (B) and Hispanic (H) individuals.
"""

from pyspark.sql.functions import collect_set, size

mental_health_races_by_state = mental_health_crisis_df.groupBy("state") \
    .agg(
        collect_set("race").alias("races_involved")
    ) \
    .withColumn("distinct_race_count", size("races_involved")) \
    .orderBy("distinct_race_count", ascending=False)

mental_health_races_by_state.show(truncate=False)

save_to_hdfs(mental_health_by_state, "/user/analysis/mental_health_by_state")
save_to_hdfs(mental_health_by_race, "/user/analysis/mental_health_by_race")
save_to_hdfs(mental_health_races_by_state, "/user/analysis/mental_health_racial_diversity")

"""These results show that California stands out with the highest racial diversity (6 distinct racial groups) in fatal police shootings involving mental health crises. States like Minnesota, Colorado, Washington, and Oklahoma follow with five groups each, suggesting a broader racial impact in these regions. This diversity may reflect demographic variation or differences in how mental health incidents involving various racial groups are handled across states. The presence of multiple racial groups in such cases highlights the importance of intersectional approaches to both mental health care and policing policies.

4. Is there any seasonal or monthly pattern to the number of fatal shootings?
"""

from pyspark.sql.functions import month, col, when, year

# Extract month from the 'date' column
dataset = dataset.withColumn("month", month(col("date")))

# Group by month and count the number of fatal shootings
monthly_counts = dataset.groupBy("month").count().orderBy("month")
monthly_counts.show()

# Group by seasons
dataset = dataset.withColumn(
    "season",
    when(col("month").isin([3, 4, 5]), "Spring")
    .when(col("month").isin([6, 7, 8]), "Summer")
    .when(col("month").isin([9, 10, 11]), "Fall")
    .otherwise("Winter")
)

# Group by season and count the number of fatal shootings
seasonal_counts = dataset.groupBy("season").count().orderBy("season")
seasonal_counts.show()

# Extract year from the 'date' column
dataset = dataset.withColumn("year", year(col("date")))

# Group by year and count the number of fatal shootings
yearly_counts = dataset.groupBy("year").count().orderBy("year")
yearly_counts.show()

save_to_hdfs(monthly_counts, "/user/analysis/monthly_fatal_shootings")
save_to_hdfs(seasonal_counts, "/user/analysis/seasonal_fatal_shootings")
save_to_hdfs(yearly_counts, "/user/analysis/yearly_fatal_shootings")

"""The analysis shows a slight seasonal variation in fatal shootings, with Spring (1,458 cases) and Winter (1,449 cases) having the highest counts, followed by Summer (1,265) and Fall (1,166). Monthly data reveals a peak in March (552) and a dip in September (363). While these differences are not extreme, they suggest some fluctuations throughout the year. Additionally, the sharp drop in 2020 (400 cases) likely reflects the impact of the COVID-19 pandemic on police activity and public behavior.

5. What percentage of fatal shootings involve (un)armed individuals?
"""

from pyspark.sql.functions import when, col, count

dataset_with_status = dataset.withColumn(
    "armed_status",
    when((col("armed").isNull()) | (col("armed") == "unarmed"), "Unarmed").otherwise("Armed")
)

armed_counts = dataset_with_status.groupBy("armed_status").agg(count("*").alias("count"))

total_shootings = dataset_with_status.count()

armed_percentages = armed_counts.withColumn(
    "percentage", (col("count") / total_shootings) * 100
)

armed_percentages.show(truncate=False)

save_to_hdfs(armed_percentages, "/user/analysis/armed_vs_unarmed_percentages")

"""6. What are the racial distributions of victims in fatal police shootings in different states?"""

from pyspark.sql.functions import col
from pyspark.sql import functions as F

grouped = dataset.groupBy("state", "race").count()

pivoted = grouped.groupBy("state").pivot("race").agg(F.first("count")).fillna(0)

pivoted.orderBy("state").show(truncate=False)


#W = White, B = Black, H = Hispanic, A = Asian, N = Native American, O = Other, NaN = Unknown or not recorde

save_to_hdfs(pivoted, "/user/analysis/race_distribution_by_state")

"""7. What is the trend in the number of fatal shootings per year? Is the number increasing or decreasing?"""

import matplotlib.pyplot as plt
from pyspark.sql.functions import year, col

dataset = dataset.withColumn("year", year(col('date')))

shootings_per_year = dataset.groupBy("year").count().orderBy("year")

shootings_per_year_df = shootings_per_year.toPandas()

shootings_per_year_df['change'] = shootings_per_year_df['count'].diff().fillna(0)

print(shootings_per_year_df[['year', 'count', 'change']])

plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.plot(shootings_per_year_df['year'], shootings_per_year_df['count'], marker='o', color='b', linestyle='-', linewidth=2)
plt.title("Number of Fatal Shootings Per Year")
plt.xlabel("Year")
plt.ylabel("Number of Fatal Shootings")
plt.grid(True)
plt.xticks(rotation=45)

plt.subplot(1, 2, 2)
plt.plot(shootings_per_year_df['year'], shootings_per_year_df['change'], marker='o', color='r', linestyle='-', linewidth=2)
plt.title("Change in Fatal Shootings Per Year")
plt.xlabel("Year")
plt.ylabel("Change in Fatal Shootings")
plt.grid(True)
plt.xticks(rotation=45)

# Show the plots
plt.tight_layout()
plt.show()

save_to_hdfs(shootings_per_year, "/user/analysis/shootings_per_year")

"""8. Are certain age groups more likely to be involved in fatal police shootings?"""

from pyspark.sql.functions import col, when, count, round

valid_ages = dataset.filter((col("age").isNotNull()) & (col("age") > 0))
age_groups = valid_ages.withColumn(
    "age_group",
    when((col("age") >= 0) & (col("age") <= 18), "0-18")
    .when((col("age") >= 19) & (col("age") <= 30), "19-30")
    .when((col("age") >= 31) & (col("age") <= 45), "31-45")
    .when((col("age") >= 46) & (col("age") <= 60), "46-60")
    .otherwise("61+")
)
result = age_groups.groupBy("age_group") \
    .agg(
        count("*").alias("count"),
        round((count("*") / valid_ages.count()) * 100, 2).alias("percentage")
    ) \
    .orderBy("count", ascending=False)

result.show(truncate=False)

save_to_hdfs(result, "/user/analysis/age_group_distribution")

"""9. Percentage of fatal police shootings where the suspect was fleeing (by foot or in a vehicle)"""

from pyspark.sql.functions import col

total_count = dataset.count()
fleeing_count = dataset.filter((col("flee") == "Foot") | (col("flee") == "Car")).count()
percentage = (fleeing_count / total_count) * 100
print(f"Percentage of fatal police shootings where the suspect was fleeing: {percentage:.2f}%")

from pyspark.sql import Row
flee_df = spark.createDataFrame([Row(percentage=f"{percentage:.2f}")])
save_to_hdfs(flee_df, "/user/analysis/fleeing_percentage")


"""## 4.2 ML algorithm implementation

In this section of the ML library implementation, we have decided to implement a couple of different machine learning algorithms to predict the manner of death (how the victim was murdered)

The values we expect to get via the algorithms implementation should identify the contributing factors to fatal police shootings and trends over regional and temporal patterns in data.

The 3 algorithms we have implemented all focus on predicting the cause of death, those are: the Random Forest, the Logistic Regression and the Gradient Boosted Tree classifier.

Evaluation techniques have differed among the algorithms, as not all of them can be analyzed with the same methodologies. Therefore, each algorithm has been evaluated with different metric techniques.
"""

from pyspark.ml.classification import RandomForestClassifier, LogisticRegression, GBTClassifier
from pyspark.ml.evaluation import MulticlassClassificationEvaluator, BinaryClassificationEvaluator
from pyspark.ml.feature import StringIndexer, VectorAssembler
from pyspark.ml import Pipeline
from pyspark.sql.functions import sum, when, udf
from pyspark.sql.functions import col
from pyspark.sql.types import StringType
from pyspark.ml.feature import StringIndexerModel
from pyspark.sql.functions import udf, col
import matplotlib.pyplot as plt
from pyspark.mllib.evaluation import BinaryClassificationMetrics
from pyspark.sql import SparkSession

def save_predictions_and_accuracy(df, accuracy_value, predictions_path, accuracy_path):
    # Save predictions
    df.select("predicted_label", "true_label") \
      .write \
      .format("csv") \
      .option("header", "true") \
      .mode("overwrite") \
      .save(predictions_path)
    
    # Save accuracy as single-row DataFrame
    spark = SparkSession.builder.getOrCreate()
    accuracy_df = spark.createDataFrame([(accuracy_value,)], ["accuracy"])
    accuracy_df.write.format("csv").option("header", "true").mode("overwrite").save(accuracy_path)


categorical_cols = ["gender", "race", "threat_level", "flee"]
numeric_cols = ["age", "signs_of_mental_illness", "body_camera"]
target_col = "manner_of_death"

cleaned_dataset = dataset.dropna(subset=["age", "gender", "race", "flee", target_col])

stages = []

for cat_col in categorical_cols:
    indexer = StringIndexer(inputCol=cat_col, outputCol=cat_col + "_indexed", handleInvalid="skip")
    stages.append(indexer)

label_indexer = StringIndexer(inputCol=target_col, outputCol="label", handleInvalid="skip")
stages.append(label_indexer)

assembler_inputs = numeric_cols + [c + "_indexed" for c in categorical_cols]
assembler = VectorAssembler(inputCols=assembler_inputs, outputCol="features")
stages.append(assembler)

"""**Random Forest**"""

rf = RandomForestClassifier(featuresCol="features", labelCol="label", numTrees=100)
stages.append(rf)

pipeline = Pipeline(stages=stages)
model = pipeline.fit(cleaned_dataset)

predictions = model.transform(cleaned_dataset)

label_indexer_model = [stage for stage in model.stages if isinstance(stage, StringIndexerModel)][-1]
labels = label_indexer_model.labels

def index_to_label(index):
    try:
        return labels[int(float(index))]
    except:
        return "Unknown"

index_to_label_udf = udf(index_to_label, StringType())

predictions_with_labels = predictions.withColumn("predicted_label", index_to_label_udf(col("prediction"))) \
                                     .withColumn("true_label", index_to_label_udf(col("label")))

predictions_with_labels.select("predicted_label", "true_label").show(10, truncate=False)

evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
accuracy = evaluator.evaluate(predictions)
print("Accuracy:", accuracy)

save_predictions_and_accuracy(
    predictions_with_labels,
    accuracy,
    "/user/analysis/predictions_random_forest",
    "/user/analysis/accuracy_random_forest"
)

"""**Logistic Regression**"""

stages = [] # We must initialize the stages array every time we run a different algorithm to run is selected

categorical_cols = ["gender", "race", "threat_level", "flee"]
numeric_cols = ["age", "signs_of_mental_illness", "body_camera"]

for cat_col in categorical_cols:
    indexer = StringIndexer(inputCol=cat_col, outputCol=cat_col + "_indexed", handleInvalid="skip")
    stages.append(indexer)

label_indexer = StringIndexer(inputCol="manner_of_death", outputCol="label", handleInvalid="skip")
stages.append(label_indexer)

assembler_inputs = numeric_cols + [c + "_indexed" for c in categorical_cols]
assembler = VectorAssembler(inputCols=assembler_inputs, outputCol="features")
stages.append(assembler)

lr = LogisticRegression(featuresCol="features", labelCol="label", maxIter=100)
stages.append(lr)

pipeline = Pipeline(stages=stages)
model = pipeline.fit(cleaned_dataset)

predictions = model.transform(cleaned_dataset)

label_indexer_model = [stage for stage in model.stages if isinstance(stage, StringIndexerModel) and stage.getOutputCol() == "label"][0]
labels = label_indexer_model.labels

def index_to_label(index):
    try:
        return labels[int(float(index))]
    except:
        return "Unknown"

index_to_label_udf = udf(index_to_label, StringType())

predictions_with_labels = predictions.withColumn("predicted_label", index_to_label_udf(col("prediction"))) \
                                     .withColumn("true_label", index_to_label_udf(col("label")))

predictions_with_labels.select("predicted_label", "true_label").show(10, truncate=False)

evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
accuracy = evaluator.evaluate(predictions)
print("Accuracy:", accuracy)

save_predictions_and_accuracy(
    predictions_with_labels,
    accuracy,
    "/user/analysis/predictions_logistic_regression",
    "/user/analysis/accuracy_logistic_regression"
)

"""**Gradient Boosted Trees Classifier**"""

stages = []

categorical_cols = ["gender", "race", "threat_level", "flee"]
numeric_cols = ["age", "signs_of_mental_illness", "body_camera"]

for cat_col in categorical_cols:
    indexer = StringIndexer(inputCol=cat_col, outputCol=cat_col + "_indexed", handleInvalid="skip")
    stages.append(indexer)

label_indexer = StringIndexer(inputCol="manner_of_death", outputCol="label", handleInvalid="skip")
stages.append(label_indexer)

assembler_inputs = numeric_cols + [c + "_indexed" for c in categorical_cols]
assembler = VectorAssembler(inputCols=assembler_inputs, outputCol="features")
stages.append(assembler)

gbt = GBTClassifier(featuresCol="features", labelCol="label", maxIter=50)
stages.append(gbt)

pipeline = Pipeline(stages=stages)
model = pipeline.fit(cleaned_dataset)

predictions = model.transform(cleaned_dataset)

label_indexer_model = [s for s in model.stages if isinstance(s, StringIndexerModel) and s.getOutputCol() == "label"][0]
labels = label_indexer_model.labels

def index_to_label(index):
    try:
        return labels[int(float(index))]
    except:
        return "Unknown"

index_to_label_udf = udf(index_to_label, StringType())

predictions_with_labels = predictions.withColumn("predicted_label", index_to_label_udf(col("prediction"))) \
                                     .withColumn("true_label", index_to_label_udf(col("label")))

predictions_with_labels.select("predicted_label", "true_label").show(10, truncate=False)

evaluator = MulticlassClassificationEvaluator(labelCol="label", predictionCol="prediction", metricName="accuracy")
accuracy = evaluator.evaluate(predictions)
print("Accuracy:", accuracy)

save_predictions_and_accuracy(
    predictions_with_labels,
    accuracy,
    "/user/analysis/predictions_gbt",
    "/user/analysis/accuracy_gbt"
)

"""**Conclusions**

While all models showed promise, Gradient Boosted Trees achieved the highest accuracy, exceeding even the robust Random Forest (95% accuracy). Logistic Regression, though interpretable, did not match the accuracy of the ensemble methods.

Gradient Boosted Trees consistently delivered the best results across various evaluation metrics, including accuracy, precision, recall, and F1-score. This suggests it's the most suitable model for this task, offering valuable insights for policy analysis and efforts to reduce fatalities in police encounters.

After all we have got considerably good results we are comfortable with and lived up to the expectations prior to this part of the work.


"""